- name: Update
  apt:
    update_cache: yes
  become: true

- name: upgrade system
  apt:
    upgrade: yes
    upgrade: dist
    update_cache: true
  become: true

- name: install vim
  apt:
    name: vim
    state: present
  become: true

- name: install python3
  apt:
    name: python3
    state: present
  become: true
